version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'CI/CD'
      - skip_changelog
    target-branch: 'main'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: "05:16"
    target-branch: 'main'
    labels:
      - dependencies
      - skip_changelog
    groups:
      pyproject:
        patterns:
          - "*"
