name: CI - Check dependencies

on:
  schedule:
    - cron: "48 4 * * 1"
  workflow_dispatch:

jobs:
  check-dependencies:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_check_pyproject_dependencies.yml@v2.6.0
    if: github.repository_owner == 'CasperWA'
    with:
      git_username: "Casper Welzel Andersen"
      git_email: "casper+github@welzel.nu"
      permanent_dependencies_branch: "main"
      python_version: "3.10"
      install_extras: "[dev]"
      pr_labels: "CI/CD"
    secrets:
      PAT: ${{ secrets.CI_TOKEN }}
